name: oscaru95
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.4+5

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6
  get_it: ^8.0.3
  get_storage: ^2.1.1
  provider: ^6.1.2
  flutter_screenutil: ^5.9.3
  dio: ^5.8.0+1
  internet_connection_checker: ^3.0.1
  flutter_displaymode: ^0.6.0
  auto_animated: ^3.2.0
  intl: ^0.19.0
  rxdart: ^0.28.0
  flutter_gen: ^5.8.0
  google_fonts: ^6.2.1
  fluttertoast: ^8.2.11
  flutter_svg: ^2.0.17
  pin_code_fields: ^8.0.1
  country_code_picker: ^3.0.0
  cached_network_image: ^3.4.0
  image_picker: ^1.1.2
  simple_gradient_text: ^1.3.0
  badges: ^3.1.2
  easy_stepper: ^0.8.5+1
  dropdown_button2: ^2.3.9
  flutter_switch: ^0.3.2
  rating_summary: ^1.0.4
  carousel_slider: ^5.0.0
  smooth_page_indicator: ^1.2.0+3
  readmore: ^3.0.0
  flutter_rating_stars: ^1.1.0
  story: ^1.1.0
  flutter_rating_bar: ^4.0.0
  syncfusion_flutter_gauges: ^28.2.7
  lottie: ^3.0.0
  intl_phone_field: ^3.2.0
  fl_chart: ^0.70.2
  google_maps_flutter: ^2.10.0
  geolocator: ^13.0.3
  geocoding: ^3.0.0
  permission_handler: ^11.4.0
  video_player: ^2.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9
  flutter_gen_runner: ^5.4.0
  flutter_lints: ^4.0.0
  dependency_validator: ^4.1.0

flutter_gen:
  output: lib/gen/
  line_length: 80

  integrations:
    flutter_svg: false
    rive: false
    lottie: false

  colors:
    inputs:
      - assets/color/colors.xml
    outputs:
      class_name: AppColors

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/lottie/
    - assets/darkthem/darkthem.json
